<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QASERVER01" ignored="0" name="ReferralIDPassing" tests="2" failures="2" timestamp="26 Nov 2019 03:33:52 GMT" time="80.574" errors="0">
  <testcase name="PassReferralID" time="30.305" classname="Tests.ReferralIDPassing">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Tests.ReferralIDPassing.PassReferralID(ReferralIDPassing.java:60)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- PassReferralID -->
  <testcase name="PassReferralID" time="30.353" classname="Tests.ReferralIDPassing">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Tests.ReferralIDPassing.PassReferralID(ReferralIDPassing.java:60)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- PassReferralID -->
</testsuite> <!-- ReferralIDPassing -->
